name: Descargar-horario-ITFIP-A2024

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Descargar-horario-ITFIP-A2024:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Descargar y subir horario
        run: |
          cd $GITHUB_WORKSPACE
          wget "https://itfip.edu.co/wp-content/uploads/Transparencia/Documentos-2024/Semestre-A-2024/Horarios-semestre-A-2024/Facultad-Ingenieria-y-Ciencias-Agroindustriales/Programa-Ingenieria-de-Sistemas/HORARIOS-ING-DE-SISTEMAS-DIA.pdf"
          ls -l HORARIOS-ING-DE-SISTEMAS-DIA.pdf
          gzip HORARIOS-ING-DE-SISTEMAS-DIA.pdf
          chmod 666 HORARIOS-ING-DE-SISTEMAS-DIA.pdf.gz

      - name: Subir Horario Descargado
        uses: actions/upload-artifact@v2
        with:
          name: HORARIOS-ING-DE-SISTEMAS-DIA
          path: HORARIOS-ING-DE-SISTEMAS-DIA.pdf.gz
